language: node_js
sudo: false
node_js:
  - node
before_script:
  - npm install -g gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp test-travis
cache:
  directories:
    - node_modules
env:
  global:
    - CXX=g++-4.8
  secure: VyNPA6QM4wenuPkMMsSHu2YtwrV3o/wFpBlDAYW4X+taHckfP8UEzgneu/SiBCgHgctUca8F7cgq5JAS+TOB6sAVpV+zxmZYvg5QAJa9edY6cFxY2rHqIgCIesQmkPGnGdRdHTTMLe0FMiPUas81UdaQ1C9Nuv5PQ4NFiZhWVte7N/LXyMTrvFyurp4VoqypBKyugVZqLskDl7/lWop9N9OZvAKw+SQxJZOR7jOrcITQaKz1niEF3sbLA4YT8y4xsegCQO07IPs75XhT3QPsz4g4RsMGSvWaEy633dxO/IHs5dUtxQG+Z3qOUIe0uGa30q660GcGMDAUyZ1bO1ZCgYHJwbgWSjsJ89QArWvH0bw6hDbAzdhUQx0Uf0QezTPJ5wMV0VJBpx8+C2CoCFYtXhAbOSX7j8HUO3nf4rDzEBCPCh3OQue+GCX2iiC0LC0rE8QjjlwIo1obJLgzuYT1hvA1qOYSbCaPAkbOiuiK2OJ3KhiLo0y3UfYbLVPHnI19ujxdRpb1W9ODA2cjjMqbEsuMmpu9Lq4xEmHIiGtVt7aUMcxXnBKmxDdqsHnQXYPa6kQB+AQS6L7B/3kG8/XQG6xofqigUOAw8Cs2fO3FP9phyVPCWs1QBtbnp5ZQOopp3CPJMQmSIkMBT0HQGfJOtbPH/3M1KpwsWjMT4Rvjv6Y=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
